#!/usr/bin/env bash
# Build the Switch's Mesa (EGL, OpenGL and nouveau: libEGL.a, libglapi.a) from source with the
# persistent shader cache, for the NRO (tools/switch/build.sh links it when it exists).
#
#   tools/switch/mesa/build_mesa.sh [--jobs N]
#
# The recipe is devkitPro's switch-mesa 20.1.0-5 package (pacman-packages switch/mesa/PKGBUILD,
# pinned below): Mesa 20.1.0-rc3 plus devkitPro's three patches, configured with
# /opt/devkitpro/meson-cross.sh switch ... -Db_ndebug=true. On top of it come patches/, from
# centollOS (the GameCube Wind Waker port, switch/mesa there, where they are tested on the host):
#   0001  newlib timespec_get clash (toolchain compatibility only)
#   0002  compile counters and timers for the log (include/mesa_switch.h)
#   0003  the disk shader cache on Horizon, one file under $MESA_SHADER_CACHE_DIR
#   0004  nvc0's code generation through that cache
# Output: build/switch-mesa/prefix/{lib,include}. The driver build's name (a hash of the source and
# every patch) keys the cache: a cache written by another build is discarded on the console.
# Sources are downloaded once into build/switch-mesa/downloads and checked against their sha256.
set -euo pipefail

root=$(cd "$(dirname "$0")/../../.." && pwd)
here=$root/tools/switch/mesa
image=${WWHD_MESA_IMAGE:-localhost/wwrecomp-switch-mesa-build:2026-10-04}

mesa_version=20.1.0-rc3
mesa_url=https://archive.mesa3d.org/older-versions/20.x/mesa-$mesa_version.tar.xz
mesa_sha256=c90b75ea34302ebde9b81b87c5642fa864c40fe9c4ad34ce0793170c1413168d
# devkitPro/pacman-packages at the commit that holds switch-mesa 20.1.0-5 (sha256 from its PKGBUILD).
dkp_commit=f103fe88e37180ecd0b7a9173b52b7580a54f71a
dkp_url=https://raw.githubusercontent.com/devkitPro/pacman-packages/$dkp_commit/switch/mesa
dkp_patches=(
    "switch-mesa-20.1.0-5.patch 950f93d3e5b6ae9c5a42c2918623fe9a80d7ee398d92d2e73abec86b62d75916"
    "gl_XML.py.patch a9bc326195b3fe29709e079466a8b2162a2ac9409f694eaad5494490155e2dd4"
    "glX_XML.py.patch 1475defcdf8600690eaddeee28d8f01310635c1273fb541f668e8789714d36ca"
)

jobs=${WWHD_JOBS:-4}
while [[ $# -gt 0 ]]; do
    case $1 in
        --jobs) jobs=$2; shift 2 ;;
        -h|--help) sed -n '2,18p' "$0"; exit 0 ;;
        *) echo "build_mesa: unknown option $1" >&2; exit 2 ;;
    esac
done

sha256() { shasum -a 256 "$1" 2>/dev/null | cut -d' ' -f1 || sha256sum "$1" | cut -d' ' -f1; }

downloads=$root/build/switch-mesa/downloads
mkdir -p "$downloads"
fetch() { # fetch URL FILE SHA256
    local url=$1 file=$downloads/$2 want=$3
    if [[ ! -f $file ]] || [[ $(sha256 "$file") != "$want" ]]; then
        echo "build_mesa: downloading $url"
        curl -fsSL -o "$file.part" "$url"
        mv "$file.part" "$file"
    fi
    if [[ $(sha256 "$file") != "$want" ]]; then
        echo "build_mesa: $file does not have sha256 $want" >&2
        exit 1
    fi
}
fetch "$mesa_url" "mesa-$mesa_version.tar.xz" "$mesa_sha256"
for entry in "${dkp_patches[@]}"; do
    fetch "$dkp_url/${entry%% *}" "${entry%% *}" "${entry##* }"
done

ours=("$here"/patches/*.patch)
work=$root/build/switch-mesa

id_input=$mesa_sha256
for entry in "${dkp_patches[@]}"; do id_input+=" ${entry##* }"; done
for p in "${ours[@]}"; do id_input+=" $(sha256 "$p")"; done
cache_id="switch-mesa-20.1.0-5+wwhd-$(printf '%s' "$id_input" | shasum -a 256 | cut -c1-16)"

engine=$(command -v podman || command -v docker || true)
if [[ -z $engine ]]; then
    echo "build_mesa: podman or docker is required" >&2
    exit 1
fi
if ! "$engine" image inspect "$image" >/dev/null 2>&1; then
    "$engine" build --tag "$image" --file "$here/Containerfile" "$here"
fi

# A fresh source tree whenever the patches change (the stamp is the cache id).
src=$work/mesa-$mesa_version
mkdir -p "$work"
if [[ ! -f $work/source.stamp ]] || [[ $(cat "$work/source.stamp") != "$cache_id" ]]; then
    rm -rf "$src" "$work/prefix"
    tar -xf "$downloads/mesa-$mesa_version.tar.xz" -C "$work"
    for entry in "${dkp_patches[@]}"; do
        patch -d "$src" -p1 -s -i "$downloads/${entry%% *}"
    done
    for p in "${ours[@]}"; do
        patch -d "$src" -p1 -s -i "$p"
    done
    printf '/* Generated by tools/switch/mesa/build_mesa.sh: the name of this driver build. */\n#define MESA_SWITCH_CACHE_ID "%s"\n' \
        "$cache_id" > "$src/include/mesa_switch_cache_id.h"
    printf '%s\n' "$cache_id" > "$work/source.stamp"
fi
echo "build_mesa: $src ($cache_id)"

if [[ $(basename "$engine") == podman ]]; then
    run=(podman run --rm --userns=keep-id -v "$root:/work:Z")
else
    run=(docker run --rm --user "$(id -u):$(id -g)" -e HOME=/tmp -v "$root:/work")
fi
"${run[@]}" -w /work -e JOBS="$jobs" -e SRCNAME="mesa-$mesa_version" "$image" bash -lc '
set -euo pipefail
cd "/work/build/switch-mesa/$SRCNAME"
if [[ ! -f build/build.ninja ]]; then
    /opt/devkitpro/meson-cross.sh switch ../crossfile.txt build -Db_ndebug=true >../meson.log 2>&1 ||
        { tail -40 ../meson.log; exit 1; }
fi
ninja -C build -j "$JOBS" >../ninja.log 2>&1 || { grep -B2 -A20 "^FAILED" ../ninja.log | head -80; exit 1; }
rm -rf ../install ../prefix
DESTDIR=/work/build/switch-mesa/install ninja -C build install >/dev/null
mkdir -p ../prefix
mv ../install/opt/devkitpro/portlibs/switch/lib ../install/opt/devkitpro/portlibs/switch/include ../prefix/
if [[ -f include/mesa_switch.h ]]; then cp include/mesa_switch.h ../prefix/include/; fi
rm -rf ../install
'
ls "$work/prefix/lib/libEGL.a" "$work/prefix/lib/libglapi.a" >/dev/null
printf '%s\n' "$cache_id" > "$work/prefix/cache_id.txt"
echo "build_mesa: built $work/prefix (cache id $cache_id)"
