#!/usr/bin/env python3
"""Generate instruction-level hooks for true 60 fps from site lists (tools/true60/sites_*.txt).

Site list lines (hex addresses; '#' starts a comment):
  ratio ADDR fR fD   per-step smoothing done by the instruction at ADDR (fmadds fD = .. fR ..):
                     fR holds the per-step ratio r; it becomes 1-(1-r)^dt for that instruction and
                     is put back after it (unless fR is also the destination)
  arg ADDR           a call at ADDR whose f1 argument is a per-step ratio r (cXyz/cSAngle operator*):
                     f1 becomes 1-(1-r)^dt

Writes runtime/src/true60_sites.cpp and the "@ADDR" lines between the markers in
tools/recomp/hooks.txt. Rerun tools/recomp/recomp.py afterwards.
"""
import glob, os, re, collections

ROOT = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
BEGIN, END = '# --- true60 sites (generated by tools/true60/gen_sites.py) ---', '# --- end of true60 sites ---'

actions = collections.defaultdict(list)  # address -> [C statements], in order
notes = collections.defaultdict(list)
for path in sorted(glob.glob(os.path.join(ROOT, 'tools/true60/sites_*.txt'))):
    group = os.path.basename(path)[6:-4]
    for line in open(path):
        comment = line.split('#', 1)[1].strip() if '#' in line else ''
        p = line.split('#')[0].split()
        if not p:
            continue
        if p[0] == 'ratio':
            a, r, d = int(p[1], 16), int(p[2][1:]), int(p[3][1:])
            actions[a].append('true60::ratio_begin(c, %d);' % r)
            if r != d:
                actions[a + 4].insert(0, 'true60::ratio_end(c, %d);' % r)
            notes[a].append('%s: %s' % (group, comment))
        elif p[0] == 'arg':
            a = int(p[1], 16)
            actions[a].append('true60::ratio_arg(c, 1);')
            notes[a].append('%s: %s' % (group, comment))
        else:
            raise SystemExit('unknown site kind: ' + line)

out = ['// Generated by tools/true60/gen_sites.py from tools/true60/sites_*.txt. Do not edit.',
       '#include "runtime.h"', '#include "true60.h"', '']
for a in sorted(actions):
    for n in notes.get(a, []):
        out.append('// %s' % n)
    out.append('extern "C" void site_%08X(Cpu* c) { %s }' % (a, ' '.join(actions[a])))
open(os.path.join(ROOT, 'runtime/src/true60_sites.cpp'), 'w').write('\n'.join(out) + '\n')

hp = os.path.join(ROOT, 'tools/recomp/hooks.txt')
text = open(hp).read()
block = BEGIN + '\n' + ''.join('@%08X\n' % a for a in sorted(actions)) + END + '\n'
if BEGIN in text:
    text = re.sub(re.escape(BEGIN) + '.*?' + re.escape(END) + '\n', lambda m: block, text, flags=re.S)
else:
    text += block
open(hp, 'w').write(text)
print('%d sites' % len(actions))
