#!/usr/bin/env python3
"""Recording taps: build the game with instrumented copies of chosen functions.

usage: mktap.py ADDR [ADDR ...]     (or: mktap.py --unit UNIT  to tap every VERIFY'd function)
       mktap.py --clean

1. writes tools/recomp/hooks_tap.txt (git-ignored) so the recompiler routes each tapped
   function through hook_ADDR, and re-runs tools/recomp/recomp.py;
2. writes build/gen/code_tap.c: tap_ADDR, a copy of the function's generated C whose own loads
   and stores and calls are logged (runtime/src/verify_tap.cpp), and hook_ADDR, which runs the
   tap copy while recording and the original otherwise.

Recording is off unless WWHD_TAP=<dir> is set when the game runs (runtime/include/verify_tap.h).
--clean removes both files and re-runs the recompiler (back to the normal build).
"""
import json
import os
import re
import subprocess
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.abspath(os.path.join(HERE, "..", ".."))
sys.path.insert(0, HERE)
from funcdb import GenIndex  # noqa: E402

HOOKS = os.path.join(ROOT, "tools", "recomp", "hooks_tap.txt")
GEN = os.path.join(ROOT, "build", "gen")
OUT = os.path.join(GEN, "code_tap.c")


def recomp():
    subprocess.run([sys.executable, "tools/recomp/recomp.py", "game/code/cking.rpx", "build/gen"], cwd=ROOT, check=True,
                   stdout=subprocess.DEVNULL)


def tap_body(text, addr, imports):
    lines = text.split("\n")
    lines[0] = "static void tap_%08X(Cpu* __restrict c) {" % addr
    out = []
    for ln in lines:
        ln = re.sub(r"MUSTTAIL return f_([0-9A-F]{8})(?:_orig)?\(c\);", lambda m: "{ tap_call(c, f_%s, 0x%sU); return; }" % (m.group(1), m.group(1)), ln)
        ln = re.sub(r"(?<![\w>])f_([0-9A-F]{8})\(c\);", lambda m: "tap_call(c, f_%s, 0x%sU);" % (m.group(1), m.group(1)), ln)
        ln = ln.replace("MUSTTAIL return ppc_dispatch(c);", "{ tap_dispatch(c); return; }")
        ln = re.sub(r"(?<![\w>])ppc_dispatch\(c\);", "tap_dispatch(c);", ln)
        ln = re.sub(r"MUSTTAIL return (imp_\w+)\(c\);", lambda m: "{ tap_call(c, %s, 0x%08XU); return; }" % (m.group(1), imports.get(m.group(1), 0)), ln)
        ln = re.sub(r"(?<![\w>])(imp_\w+)\(c\);", lambda m: "tap_call(c, %s, 0x%08XU);" % (m.group(1), imports.get(m.group(1), 0)), ln)
        out.append(ln)
    return "\n".join(out)


def main():
    args = sys.argv[1:]
    if args == ["--clean"]:
        for p in (HOOKS, OUT):
            if os.path.exists(p):
                os.remove(p)
        recomp()
        print("taps removed")
        return
    addrs = []
    if args[:1] == ["--unit"]:
        for line in open(os.path.join(HERE, "units", args[1] + ".txt")):
            f = line.split("#")[0].split()
            if f and f[0] == "src":
                for s in f[1:]:
                    addrs += [int(m, 16) for m in re.findall(r"^\s*VERIFY\(\s*0x([0-9A-Fa-f]{8})", open(os.path.join(ROOT, s)).read(), re.M)]
        args = args[2:]
    addrs += [int(a, 16) for a in args]
    addrs = sorted(set(addrs))
    with open(HOOKS, "w") as f:
        f.write("# generated by tools/verify/mktap.py (recording taps); remove with mktap.py --clean\n")
        for a in addrs:
            f.write("%08X\n" % a)
    recomp()
    gen = GenIndex(GEN, cache=os.path.join(ROOT, "build", "verify", "genindex_tap.pkl"))
    imports = {}
    for e in json.load(open(os.path.join(GEN, "imports.json"))):
        if e["kind"] == "f":
            ident = "imp_%s_%s" % (re.sub(r"[^A-Za-z0-9_]", "_", e["lib"].replace(".rpl", "")), re.sub(r"[^A-Za-z0-9_]", "_", e["name"]))
            imports[ident] = e["slot"]
    out = ['/* generated by tools/verify/mktap.py: recording taps (build output) */', '#include "funcs.h"',
           '#include "verify_tap_gen.h"', ""]
    for a in addrs:
        if not gen.loc[a][3]:
            sys.exit("%08X is not hooked after recompiling (missing from hooks?)" % a)
        out.append(tap_body(gen.text(a), a, imports))
        out.append("void hook_%08X(Cpu* c) {\n    if (tap_begin(c, 0x%08XU)) { tap_%08X(c); tap_end(c); }\n    else f_%08X_orig(c);\n}\n" % (a, a, a, a))
    open(OUT, "w").write("\n".join(out))
    print("tapped %d functions -> %s" % (len(addrs), os.path.relpath(OUT, ROOT)))


if __name__ == "__main__":
    main()
