#!/usr/bin/env python3
"""Build a verification unit: the recompiled originals of the functions a candidate source
implements, isolated from the rest of the game.

usage: mkunit.py UNIT [--root .] [--out build/verify/UNIT]

Reads tools/verify/units/UNIT.txt:
    src  wwhd_src/...cpp        candidate sources (VERIFY(0xADDR, fn) marks what they implement)
    real ADDR                   link this callee's real code instead of a mock (pure helpers)
    field ADDR|* rN+OFF TYPE LO [HI]   steer generated inputs (read by the harness, -spec)

Writes OUT/unit.c: each tested function's generated C (renamed orig_X, memory accesses through
the harness, basic-block coverage points), real callees (real_X), a stub for every other guest
function or import they reference (records the call: vm_call), and the callee table (which
argument registers to compare, which registers a mock may write, pointer argument sizes).
"""
import argparse
import json
import os
import re
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from funcdb import (GenIndex, load_names, signature, arg_regs, stack_words, Dataflow, RetWidth, CALL_RE, INT_ARGS, FLT_ARGS)

IMP_RE = re.compile(r"\b(imp_\w+)\(c\)")
SITE_RE = re.compile(r"\b(site_[0-9A-F]{8})\(c\)")


def read_unit(path):
    u = {"src": [], "real": []}
    for line in open(path):
        line = line.split("#")[0].split()
        if not line:
            continue
        if line[0] == "src":
            u["src"] += line[1:]
        elif line[0] == "real":
            u["real"] += [int(x, 16) for x in line[1:]]
        elif line[0] == "callee":
            for kv in line[2:]:
                k, v = kv.split("=")
                u.setdefault("over", {})[(int(line[1], 16), k)] = int(v, 0)
    return u


def instrument(text, new_name, cov):
    """rename the function, add coverage points at block starts"""
    lines = text.split("\n")
    out = []
    nb = 0
    m = re.match(r"void (f_[0-9A-F]{8}(?:_orig)?)\(", lines[0])
    out.append("void %s(Cpu* __restrict c) {" % new_name)
    pending = cov
    if cov:
        out.append("    VM_COV(0, %d);" % nb)
        nb += 1
    for ln in lines[1:]:
        # a hooked neighbour (runtime hook or recording tap) is reached as f_X_orig: same function
        ln = re.sub(r"\bf_([0-9A-F]{8})_orig\(c\)", r"f_\1(c)", ln)
        out.append(ln)
        if not cov:
            continue
        s = ln.strip()
        if ln.startswith("L_"):
            out.append("    VM_COV(0, %d);" % nb)
            nb += 1
        elif s.startswith("if (") or s.startswith("c->ctr--; if ("):
            out.append("    VM_COV(0, %d);" % nb)
            nb += 1
    return "\n".join(out), nb


def pointee_size(t):
    if t is None or t.kind not in ("ptr", "ref") or t.inner is None:
        return 0
    i = t.inner
    if i.kind in ("int", "float"):
        return i.size
    if i.kind == "class":
        return i.size
    if i.kind == "array":  # Mtx: float[4]* (row pointer)
        return 48 if i.name.startswith("float[4]") else (i.size or 0)
    return 0


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("unit")
    ap.add_argument("--root", default=".")
    ap.add_argument("--out")
    a = ap.parse_args()
    root = os.path.abspath(a.root)
    build = os.path.join(root, "build")
    out = a.out or os.path.join(build, "verify", a.unit)
    os.makedirs(out, exist_ok=True)
    unit = read_unit(os.path.join(root, "tools", "verify", "units", a.unit + ".txt"))
    tested = []
    for s in unit["src"]:
        for m in re.finditer(r"^\s*VERIFY\(\s*0x([0-9A-Fa-f]{8})\s*,", open(os.path.join(root, s)).read(), re.M):
            tested.append(int(m.group(1), 16))
    tested = sorted(set(tested))
    gen = GenIndex(os.path.join(build, "gen"))
    names, gc = load_names(build)
    df = Dataflow(gen)
    df_lo = Dataflow(gen, unknown_reads_args=False)  # registers the code itself reads (no guesses for indirect calls)
    rw = RetWidth(df)
    imports = {}
    ij = os.path.join(build, "gen", "imports.json")
    for e in json.load(open(ij)):
        if e["kind"] == "f":
            ident = "imp_%s_%s" % (re.sub(r"[^A-Za-z0-9_]", "_", e["lib"].replace(".rpl", "")), re.sub(r"[^A-Za-z0-9_]", "_", e["name"]))
            imports[ident] = (e["slot"], e["name"])

    body = ['/* generated by tools/verify/mkunit.py: unit %s (recompiled originals; build output, do not commit) */' % a.unit,
            '#include "vm_gen.h"', '#include "unit.h"', ""]
    callees, imps, sites = set(), set(), set()
    funcs_c, origs = [], []
    for addr, prefix in [(x, "orig") for x in tested] + [(x, "real") for x in unit["real"]]:
        if addr not in gen.loc:
            sys.exit("no generated function at %08X" % addr)
        text = gen.text(addr)
        for m in CALL_RE.finditer(text):
            callees.add(int(m.group(1), 16))
        imps |= set(IMP_RE.findall(text))
        sites |= set(SITE_RE.findall(text))
        t, nb = instrument(text, "%s_%08X" % (prefix, addr), prefix == "orig")
        funcs_c.append(t)
        if prefix == "orig":
            origs.append((addr, nb))
    real = set(unit["real"])
    callees |= real
    overrides = unit.get("over", {})
    decls = ["void f_%08X(Cpu* c);" % x for x in sorted(callees)]
    decls += ["void %s(Cpu* c);" % x for x in sorted(imps)]
    decls += ["void %s(Cpu* c);" % x for x in sorted(sites)]
    decls += ["void real_%08X(Cpu* c);" % x for x in sorted(real)]
    body += decls + [""] + funcs_c + [""]
    body.append("/* calls out of the unit: recorded by the harness */")
    for x in sorted(callees):
        body.append("void f_%08X(Cpu* c) { vm_call(c, 0x%08Xu, VM_CALL_DIRECT); }" % (x, x))
    for x in sorted(imps):
        slot = imports.get(x, (0, x))[0]
        body.append("void %s(Cpu* c) { vm_call(c, 0x%08Xu, VM_CALL_IMPORT); }" % (x, slot))
    for x in sorted(sites):
        body.append("void %s(Cpu* c) { (void)c; } /* runtime instruction hook: not part of the game's code */" % x)

    def mask(regs):
        m = 0
        for r in regs:
            m |= 1 << r
        return m

    rows = []
    allc = sorted(callees) + [imports[x][0] for x in sorted(imps) if x in imports]
    for x in allc:
        is_imp = x not in gen.loc
        nm = names.get(x, ("",))[0] if not is_imp else next(v[1] for k, v in imports.items() if v[0] == x)
        sym = gc.get(x, ("",))[0]
        sig = signature(sym) if sym else None
        ptrsz = [0] * 11
        outp = [0] * 11
        declared = 0
        nstack = 0
        rk, rb, rc = 0, 0, 0
        if is_imp:
            im, fm = 0, 0
            declared = 1
            defr, deff = 0xFFFFFFFF, 0xFFFFFFFF
        else:
            w = rw.width(x)
            if w:
                rk, rb, rc = {"u": (1, w[1], 0), "s": (2, w[1], 0), "const": (3, 32, w[1])}[w[0]]
            li = df.livein(x)
            md = df.maydef(x)
            defr = mask(r for k, r in md if k == "r")
            deff = mask(r for k, r in md if k == "f")
            # compared registers: what the callee's code reads (sound unless it reads them only
            # through indirect calls) plus the GameCube signature's arguments (the matcher can be
            # wrong about the name, so the signature never narrows the set)
            if df.cfg(x).varargs:
                declared = 1  # variadic: also compare what the candidate passes
            lo = df_lo.livein(x)
            im = mask(r for k, r in lo if k == "r")
            fm = mask(r for k, r in lo if k == "f")
            if sig:
                method, params = sig
                ints, flts, types = arg_regs(method and ("r", 3) in li, params)
                im |= mask(ints)
                fm |= mask(flts)
                nstack = stack_words(method and ("r", 3) in li, params)
                for reg, t in types.items():
                    if reg[0] == "r":
                        n = int(reg[1:])
                        ptrsz[n] = pointee_size(t)
                        outp[n] = int(t.kind in ("ptr", "ref") and t.inner is not None and not t.inner.const)
        rl = "real_%08X" % x if x in real else "0"
        # a constructor initialises its object: what was in the storage before is not an input
        if sym.startswith("__ct__") or nm.endswith("::ct") or nm.endswith("_ct"):
            ptrsz[3] = 255
        nstack = max(nstack, overrides.get((x, "stack"), 0))
        for reg in range(3, 11):
            if (x, "r%d" % reg) in overrides:
                ptrsz[reg] = overrides[(x, "r%d" % reg)]
        rows.append('    {0x%08Xu, "%s", 0x%Xu, 0x%Xu, 0x%Xu, 0x%Xu, {%s}, {%s}, %s, %d, %d, %d, 0x%Xu, %d},' % (
            x, nm.replace('"', ""), im, fm, defr, deff, ",".join(map(str, ptrsz)), ",".join(map(str, outp)), rl,
            declared, rk, rb, rc, nstack))
    body.append("\nconst CalleeInfo unit_callees[] = {\n%s\n    {0}\n};" % "\n".join(rows))
    body.append("const unsigned unit_ncallees = %d;" % len(rows))
    rows = []
    for addr, nb in origs:
        sym = gc.get(addr, ("",))[0]
        sig = signature(sym) if sym else None
        argt = ["x"] * 11
        nflt = 0
        li = df.livein(addr)
        if sig:
            method, params = sig
            ints, flts, types = arg_regs(method, params)
            for reg, t in types.items():
                if reg[0] == "r":
                    n = int(reg[1:])
                    if t.kind in ("ptr", "ref"):
                        argt[n] = "p"
                    elif t.name in ("short", "sshort"):
                        argt[n] = "h"
                    elif t.name == "ushort":
                        argt[n] = "H"
                    elif t.name in ("char", "schar"):
                        argt[n] = "c"
                    elif t.name in ("uchar", "bool"):
                        argt[n] = "b"
                    elif t.kind == "int":
                        argt[n] = "i"
            nflt = len(flts)
        rows.append('    {0x%08Xu, "%s", "%s", orig_%08X, %d, "%s", %d, 0x%Xu, 0x%Xu},' % (
            addr, names.get(addr, ("",))[0], sym, addr, nb, "".join(argt), nflt,
            mask(r for k, r in li if k == "r"), mask(r for k, r in li if k == "f")))
    body.append("\nconst OrigFunc unit_funcs[] = {\n%s\n};" % "\n".join(rows))
    body.append("const unsigned unit_nfuncs = %d;" % len(rows))
    body.append('const char unit_name[] = "%s";' % a.unit)
    open(os.path.join(out, "unit.c"), "w").write("\n".join(body) + "\n")
    print("unit %s: %d functions under test, %d callees, %d imports -> %s" % (a.unit, len(origs), len(callees), len(imps), out))


if __name__ == "__main__":
    main()
