// Teleport destinations for the settings overlay (Switch tab "Warp"), from centollOS's PC menu
// (native/src/pc/features/pc_menu.cpp there): stage, room, spawn point. The sea's rooms are its 7x7
// grid squares (A1 = 1). The full list is every stage of the HD disc (content/Common/Stage) with the
// start centollOS's boot sweep found; the GameCube's test stages, absent from HD, are left out.
#pragma once

namespace mods {

struct Warp {
    const char* stage;
    int room;
    int point;
    const char* label;  // nullptr: the stage name
};

inline constexpr Warp kMainWarps[] = {
    {"sea", 44, 206, "Outset Island (Isla Initia)"},
    {"LinkRM", 0, 0, "Link's house (Casa del heroe)"},
    {"sea", 11, 0, "Windfall Island (Isla Taura)"},
    {"sea", 13, 0, "Dragon Roost Island (Isla del Dragon)"},
    {"M_NewD2", 0, 0, "Dragon Roost Cavern (Caverna del Dragon)"},
    {"sea", 41, 0, "Forest Haven, sea (Isla del Bosque)"},
    {"Omori", 0, 3, "Forest Haven, inside (Refugio del Bosque)"},
    {"kindan", 0, 0, "Forbidden Woods (Bosque Prohibido)"},
    {"sea", 26, 0, "Tower of the Gods, sea (Torre de los Dioses)"},
    {"Siren", 0, 0, "Tower of the Gods (Torre de los Dioses)"},
    {"sea", 1, 0, "Forsaken Fortress, sea (Fortaleza Maldita)"},
    {"MajyuE", 0, 0, "Forsaken Fortress (Fortaleza Maldita)"},
    {"Hyrule", 0, 0, "Hyrule Castle (Castillo sumergido)"},
    {"sea", 45, 0, "Headstone Island (Isla Lapida)"},
    {"M_Dai", 0, 0, "Earth Temple (Templo de la Tierra)"},
    {"sea", 4, 0, "Gale Isle (Isla del Vendaval)"},
    {"kaze", 15, 15, "Wind Temple (Templo del Viento)"},
    {"GanonK", 0, 0, "Ganon's Tower (Torre de Ganon)"},
};

inline constexpr Warp kAllWarps[] = {
    {"ADMumi", 0, 100, nullptr},
    {"A_mori", 0, 0, nullptr},
    {"A_nami", 0, 0, nullptr},
    {"A_umikz", 0, 0, nullptr},
    {"Abesso", 0, 0, nullptr},
    {"Abship", 0, 0, nullptr},
    {"Adanmae", 0, 0, nullptr},
    {"Asoko", 0, 0, nullptr},
    {"Atorizk", 0, 0, nullptr},
    {"Cave01", 0, 0, nullptr},
    {"Cave02", 0, 0, nullptr},
    {"Cave03", 0, 0, nullptr},
    {"Cave04", 0, 0, nullptr},
    {"Cave05", 0, 0, nullptr},
    {"Cave06", 0, 0, nullptr},
    {"Cave07", 0, 0, nullptr},
    {"Cave08", 0, 0, nullptr},
    {"Cave09", 0, 0, nullptr},
    {"Cave10", 1, 0, nullptr},
    {"Cave11", 1, 0, nullptr},
    {"Comori", 0, 0, nullptr},
    {"DmSpot0", 0, 0, nullptr},
    {"E3ROOP", 0, 0, nullptr},
    {"ENDumi", 0, 0, nullptr},
    {"Ebesso", 0, 0, nullptr},
    {"Edaichi", 0, 0, nullptr},
    {"Ekaze", 0, 0, nullptr},
    {"Fairy01", 0, 0, nullptr},
    {"Fairy02", 0, 0, nullptr},
    {"Fairy03", 0, 0, nullptr},
    {"Fairy04", 0, 0, nullptr},
    {"Fairy05", 0, 0, nullptr},
    {"Fairy06", 0, 0, nullptr},
    {"GTower", 0, 0, nullptr},
    {"GanonA", 0, 0, nullptr},
    {"GanonB", 0, 0, nullptr},
    {"GanonC", 0, 0, nullptr},
    {"GanonD", 0, 0, nullptr},
    {"GanonE", 0, 0, nullptr},
    {"GanonJ", 1, 0, nullptr},
    {"GanonK", 0, 0, nullptr},
    {"GanonL", 0, 0, nullptr},
    {"GanonM", 0, 0, nullptr},
    {"GanonN", 0, 0, nullptr},
    {"Hyroom", 0, 0, nullptr},
    {"Hyrule", 0, 0, nullptr},
    {"ITest61", 0, 0, nullptr},
    {"ITest62", 0, 0, nullptr},
    {"ITest63", 0, 0, nullptr},
    {"I_SubAN", 9, 0, nullptr},
    {"Kaisen", 0, 0, nullptr},
    {"LinkRM", 0, 1, nullptr},
    {"LinkUG", 0, 1, nullptr},
    {"M2ganon", 0, 0, nullptr},
    {"M2tower", 0, 16, nullptr},
    {"M_Dai", 0, 0, nullptr},
    {"M_DaiB", 0, 0, nullptr},
    {"M_DaiMB", 12, 0, nullptr},
    {"M_Dra09", 9, 0, nullptr},
    {"M_DragB", 0, 0, nullptr},
    {"M_NewD2", 0, 0, nullptr},
    {"MajyuE", 0, 0, nullptr},
    {"MiniHyo", 0, 0, nullptr},
    {"MiniKaz", 0, 0, nullptr},
    {"Mjtower", 0, 16, nullptr},
    {"Msmoke", 0, 0, nullptr},
    {"Mukao", 0, 0, nullptr},
    {"Nitiyou", 0, 0, nullptr},
    {"Obombh", 0, 0, nullptr},
    {"Obshop", 1, 0, nullptr},
    {"Ocean", 0, 0, nullptr},
    {"Ocmera", 0, 0, nullptr},
    {"Ocrogh", 0, 0, nullptr},
    {"Ojhous", 0, 0, nullptr},
    {"Ojhous2", 1, 0, nullptr},
    {"Omasao", 0, 0, nullptr},
    {"Omori", 0, 0, nullptr},
    {"Onobuta", 0, 0, nullptr},
    {"Opub", 0, 0, nullptr},
    {"Orichh", 0, 0, nullptr},
    {"Otkura", 0, 0, nullptr},
    {"PShip", 0, 0, nullptr},
    {"PShip2", 0, 0, nullptr},
    {"PShip3", 0, 0, nullptr},
    {"Pdrgsh", 0, 0, nullptr},
    {"Pfigure", 0, 0, nullptr},
    {"Pjavdou", 0, 0, nullptr},
    {"Pnezumi", 0, 0, nullptr},
    {"ShipD", 0, 0, nullptr},
    {"Siren", 0, 0, nullptr},
    {"SirenB", 0, 0, nullptr},
    {"SirenMB", 23, 0, nullptr},
    {"SubD42", 0, 0, nullptr},
    {"SubD43", 0, 0, nullptr},
    {"SubD44", 0, 0, nullptr},
    {"SubD51", 0, 0, nullptr},
    {"SubD71", 0, 0, nullptr},
    {"TF_01", 0, 0, nullptr},
    {"TF_02", 0, 0, nullptr},
    {"TF_03", 0, 0, nullptr},
    {"TF_04", 0, 0, nullptr},
    {"TF_06", 0, 0, nullptr},
    {"TyuTyu", 0, 0, nullptr},
    {"WarpD", 0, 0, nullptr},
    {"Xboss0", 0, 0, nullptr},
    {"Xboss1", 0, 0, nullptr},
    {"Xboss2", 0, 0, nullptr},
    {"Xboss3", 0, 0, nullptr},
    {"figureA", 0, 0, nullptr},
    {"figureB", 0, 0, nullptr},
    {"figureC", 0, 0, nullptr},
    {"figureD", 0, 0, nullptr},
    {"figureE", 0, 0, nullptr},
    {"figureF", 0, 0, nullptr},
    {"figureG", 0, 0, nullptr},
    {"kazan", 0, 0, nullptr},
    {"kaze", 15, 15, nullptr},
    {"kazeB", 0, 0, nullptr},
    {"kazeMB", 6, 0, nullptr},
    {"kenroom", 0, 0, nullptr},
    {"kinBOSS", 0, 0, nullptr},
    {"kinMB", 10, 0, nullptr},
    {"kindan", 0, 0, nullptr},
    {"ma2room", 0, 0, nullptr},
    {"ma3room", 0, 0, nullptr},
    {"majroom", 0, 0, nullptr},
    {"sea", 1, 0, nullptr},
    {"sea_E", 0, 0, nullptr},
    {"sea_T", 44, 0, nullptr},
    {"tincle", 0, 0, nullptr},
};

}  // namespace mods
