# Writes OUT (a C++ source with build::version() and build::commit(), runtime/src/build_info.h) on
# every build, rewriting it only when the text changes (so a rebuild recompiles one small file only
# after a new commit). Run as: cmake -DSRC=<source dir> -DOUT=<file> [-DVERSION=<tag>] -P BuildInfo.cmake
#
# version: VERSION when given (release builds: the tag, e.g. v0.2.5; .github/workflows/release.yml),
#   else from the newest v* tag: "v0.2.5" on the tagged commit, "v0.2.5+3" three commits after it,
#   "dev" without git or tags (a source archive)
# commit:  the short commit hash, "-dirty" with uncommitted changes to tracked files, "unknown" without git
set(version "${VERSION}")
set(commit "unknown")
find_package(Git QUIET)
if(GIT_FOUND AND EXISTS "${SRC}/.git")
  execute_process(COMMAND "${GIT_EXECUTABLE}" -C "${SRC}" rev-parse --short=7 HEAD
                  OUTPUT_VARIABLE head OUTPUT_STRIP_TRAILING_WHITESPACE ERROR_QUIET RESULT_VARIABLE rc)
  if(rc EQUAL 0 AND head)
    set(commit "${head}")
    execute_process(COMMAND "${GIT_EXECUTABLE}" -C "${SRC}" diff --quiet HEAD -- RESULT_VARIABLE dirty
                    OUTPUT_QUIET ERROR_QUIET)
    if(dirty EQUAL 1)
      string(APPEND commit "-dirty")
    endif()
  endif()
  if(NOT version)
    execute_process(COMMAND "${GIT_EXECUTABLE}" -C "${SRC}" describe --tags --long --match "v[0-9]*" HEAD
                    OUTPUT_VARIABLE desc OUTPUT_STRIP_TRAILING_WHITESPACE ERROR_QUIET RESULT_VARIABLE rc)
    if(rc EQUAL 0 AND desc MATCHES "^(.+)-([0-9]+)-g[0-9a-f]+$")
      set(version "${CMAKE_MATCH_1}")
      if(NOT CMAKE_MATCH_2 EQUAL 0)
        string(APPEND version "+${CMAKE_MATCH_2}")
      endif()
    endif()
  endif()
endif()
if(NOT version)
  set(version "dev")
endif()
# no quotes or backslashes in the C string
string(REGEX REPLACE "[\"\\\\]" "" version "${version}")

set(text "// generated by cmake/BuildInfo.cmake; do not edit
#include \"build_info.h\"
namespace build {
const char* version() { return \"${version}\"; }
const char* commit() { return \"${commit}\"; }
}  // namespace build
")
set(old "")
if(EXISTS "${OUT}")
  file(READ "${OUT}" old)
endif()
if(NOT old STREQUAL text)
  file(WRITE "${OUT}" "${text}")
endif()
